// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/v1/kv.proto

// etcdx 的 KV API 定义。
// 这是客户端（etcdxctl 等）与服务端 (etcdx-server) 之间唯一的契约。
// 任何字段调整都要保持 proto3 兼容性：不要改 tag 号、不要改字段类型。

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyValue 是 etcdx 里"一份键值数据"的标准表示。
// 不只是 (key, value) 两个字段——还携带 MVCC 元数据用于支持 Watch、版本对比等。
type KeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户的 key。bytes 而非 string：允许任意二进制内容，不强制 UTF-8。
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 用户的 value。同上，可以是任意字节。
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// 这个 key 第一次被创建时分配的 revision。
	// 用途：检测 "这个 key 是不是新插入的" —— 如果 create_revision == mod_revision，
	//
	//	说明本次写入就是首次创建；否则是覆盖更新。
	CreateRevision int64 `protobuf:"varint,3,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	// 这个 key 最近一次被修改时的 revision。每次 Put/Delete 都会刷新 mod_revision。
	// 用途：
	//  1. Watch 客户端用它判断"我有没有漏接事件"（事件流必须连续递增）
	//  2. 客户端做乐观并发：先 Range 拿到 mod_revision，再 Put 时携带它做 CAS
	ModRevision   int64 `protobuf:"varint,4,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_api_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *KeyValue) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要写入的 key（必填，不能为空）。
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 要写入的 value。可以为空字节串（代表"占位 key"，但仍会分配 revision）。
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// 是否要在响应里带回旧值。
	// 默认 false —— 不需要旧值时可以省去一次 bbolt 读取，减少延迟。
	// true 时服务端会在写入前先读取当前值放到 PutResponse.prev_kv。
	PrevKv        bool `protobuf:"varint,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本次 Put 操作分配到的全局 revision（单调递增，全集群一致）。
	// 客户端可以用它和后续 Watch 事件做去重 / 顺序校验。
	Revision int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// 旧值。仅当 PutRequest.prev_kv == true 且 key 之前存在时才有值；
	// 否则该字段为 nil。
	// 注意 proto3 的 message 字段天然可空（nil 表示 "未设置"）。
	PrevKv        *KeyValue `protobuf:"bytes,2,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *PutResponse) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type RangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 范围起点（含）。
	// 单 key 查询时这就是要查的那个 key。
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 范围终点（不含）。三种约定：
	//  1. range_end 为空 (len=0)            -> 单 key 查询，只返回 key 这一个
	//  2. range_end = single byte 0x00      -> 查询所有 ≥ key 的 key（全量）
	//  3. range_end 为其他值                 -> 半开区间 [key, range_end)，
	//     常用于前缀扫描（end = prefix 自增一位）
	//
	// 这个约定和 etcd 官方 v3 API 保持一致，便于将来切换 SDK。
	RangeEnd      []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_api_v1_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{3}
}

func (x *RangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

type RangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 命中的 KV 列表。按 key 字典序升序排列。
	// 空范围（无命中）时返回空切片，不是 error。
	Kvs []*KeyValue `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	// 当前 store 的最新 revision（不是查询结果的 revision）。
	// 客户端可以拿它作为后续 Watch 的起始点：
	//
	//	"从 revision+1 开始监听，保证不漏不重"
	Revision      int64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_api_v1_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{4}
}

func (x *RangeResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *RangeResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 删除范围起点（含）。同 RangeRequest.key。
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 删除范围终点（不含）。同 RangeRequest.range_end，三种约定一致。
	// 这样 Delete 既能删单 key、也能删前缀、也能删全部，接口统一。
	RangeEnd []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// 是否在响应里返回被删除的 KV 内容。
	// 用途：审计、回滚、把被删除的数据写到外部归档等。
	PrevKv        bool `protobuf:"varint,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_v1_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *DeleteRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 实际删除的 key 数量。可能为 0（范围内没有 key）。
	Deleted int64 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// 被删除的所有 KV 内容。仅当 DeleteRequest.prev_kv == true 时非空。
	PrevKvs []*KeyValue `protobuf:"bytes,2,rep,name=prev_kvs,json=prevKvs,proto3" json:"prev_kvs,omitempty"`
	// 本次 Delete 操作的 revision（即使删除了多个 key，整个 Delete 也只占用一个 revision）。
	// 这个语义与 etcd 一致：一次 RPC 调用对应一个原子提交，分配一个 revision。
	Revision      int64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_v1_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteResponse) GetPrevKvs() []*KeyValue {
	if x != nil {
		return x.PrevKvs
	}
	return nil
}

func (x *DeleteResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_api_v1_kv_proto protoreflect.FileDescriptor

const file_api_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/v1/kv.proto\x12\fetcdx.api.v1\"~\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12'\n" +
	"\x0fcreate_revision\x18\x03 \x01(\x03R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x04 \x01(\x03R\vmodRevision\"M\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x17\n" +
	"\aprev_kv\x18\x03 \x01(\bR\x06prevKv\"Z\n" +
	"\vPutResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12/\n" +
	"\aprev_kv\x18\x02 \x01(\v2\x16.etcdx.api.v1.KeyValueR\x06prevKv\"=\n" +
	"\fRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\"U\n" +
	"\rRangeResponse\x12(\n" +
	"\x03kvs\x18\x01 \x03(\v2\x16.etcdx.api.v1.KeyValueR\x03kvs\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\"W\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12\x17\n" +
	"\aprev_kv\x18\x03 \x01(\bR\x06prevKv\"y\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\x121\n" +
	"\bprev_kvs\x18\x02 \x03(\v2\x16.etcdx.api.v1.KeyValueR\aprevKvs\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision2\xc7\x01\n" +
	"\x02KV\x12:\n" +
	"\x03Put\x12\x18.etcdx.api.v1.PutRequest\x1a\x19.etcdx.api.v1.PutResponse\x12@\n" +
	"\x05Range\x12\x1a.etcdx.api.v1.RangeRequest\x1a\x1b.etcdx.api.v1.RangeResponse\x12C\n" +
	"\x06Delete\x12\x1b.etcdx.api.v1.DeleteRequest\x1a\x1c.etcdx.api.v1.DeleteResponseB#Z!github.com/lccxxo/etcdx/api/v1;v1b\x06proto3"

var (
	file_api_v1_kv_proto_rawDescOnce sync.Once
	file_api_v1_kv_proto_rawDescData []byte
)

func file_api_v1_kv_proto_rawDescGZIP() []byte {
	file_api_v1_kv_proto_rawDescOnce.Do(func() {
		file_api_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_kv_proto_rawDesc), len(file_api_v1_kv_proto_rawDesc)))
	})
	return file_api_v1_kv_proto_rawDescData
}

var file_api_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_kv_proto_goTypes = []any{
	(*KeyValue)(nil),       // 0: etcdx.api.v1.KeyValue
	(*PutRequest)(nil),     // 1: etcdx.api.v1.PutRequest
	(*PutResponse)(nil),    // 2: etcdx.api.v1.PutResponse
	(*RangeRequest)(nil),   // 3: etcdx.api.v1.RangeRequest
	(*RangeResponse)(nil),  // 4: etcdx.api.v1.RangeResponse
	(*DeleteRequest)(nil),  // 5: etcdx.api.v1.DeleteRequest
	(*DeleteResponse)(nil), // 6: etcdx.api.v1.DeleteResponse
}
var file_api_v1_kv_proto_depIdxs = []int32{
	0, // 0: etcdx.api.v1.PutResponse.prev_kv:type_name -> etcdx.api.v1.KeyValue
	0, // 1: etcdx.api.v1.RangeResponse.kvs:type_name -> etcdx.api.v1.KeyValue
	0, // 2: etcdx.api.v1.DeleteResponse.prev_kvs:type_name -> etcdx.api.v1.KeyValue
	1, // 3: etcdx.api.v1.KV.Put:input_type -> etcdx.api.v1.PutRequest
	3, // 4: etcdx.api.v1.KV.Range:input_type -> etcdx.api.v1.RangeRequest
	5, // 5: etcdx.api.v1.KV.Delete:input_type -> etcdx.api.v1.DeleteRequest
	2, // 6: etcdx.api.v1.KV.Put:output_type -> etcdx.api.v1.PutResponse
	4, // 7: etcdx.api.v1.KV.Range:output_type -> etcdx.api.v1.RangeResponse
	6, // 8: etcdx.api.v1.KV.Delete:output_type -> etcdx.api.v1.DeleteResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_kv_proto_init() }
func file_api_v1_kv_proto_init() {
	if File_api_v1_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_kv_proto_rawDesc), len(file_api_v1_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_kv_proto_goTypes,
		DependencyIndexes: file_api_v1_kv_proto_depIdxs,
		MessageInfos:      file_api_v1_kv_proto_msgTypes,
	}.Build()
	File_api_v1_kv_proto = out.File
	file_api_v1_kv_proto_goTypes = nil
	file_api_v1_kv_proto_depIdxs = nil
}
